graph TD
    A[Archinalysator] --> B[src]
    B --> md[.md files: 16]
    B --> rs[.rs files: 15]
    B --> lock[.lock files: 1]
    B --> tsx[.tsx files: 2]
    B --> exe[.exe files: 4]
    B --> toml[.toml files: 1]
    B --> gz[.gz files: 1]
    B --> tgz[.tgz files: 2]
    B --> json[.json files: 19]
    B --> svg[.svg files: 4]
    B --> ico[.ico files: 1]
    B --> js[.js files: 15]
    B --> png[.png files: 1]
    B --> txt[.txt files: 1]
    B --> cjs[.cjs files: 5]
    B --> ts[.ts files: 2]
    B --> html[.html files: 2]

    %% #ДОДЕЛАТЬ: Требуется анализ зависимостей между модулями
